# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-05 13:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alternative1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='owner_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='alternative1.Group'),
        ),
        migrations.AlterField(
            model_name='task',
            name='owner_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='alternative1.Person'),
        ),
    ]
