# Generated by Django 3.1.4 on 2020-12-07 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alternative1', '0002_auto_20161105_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='alternative1.person'),
        ),
    ]
