# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-05 07:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gfks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='gfks.Person'),
            preserve_default=False,
        ),
    ]
