# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 12:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postcode', models.CharField(blank=True, max_length=11, verbose_name='postcode')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations_as_owner', to='accounts.Profile')),
                ('tenants', models.ManyToManyField(blank=True, related_name='locations_as_tenant', to='accounts.Profile')),
            ],
        ),
    ]
