# Generated by Django 3.1.4 on 2020-12-07 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alternative2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='alternative2.person'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='group',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='alternative2.group'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='person',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='alternative2.person'),
        ),
    ]
