# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-05 17:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alternative3', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='owner',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='alternative3.Owner'),
            preserve_default=False,
        ),
    ]
