# Generated by Django 3.1.4 on 2020-12-07 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alternative3', '0002_group_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='alternative3.person'),
        ),
        migrations.AlterField(
            model_name='group',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='group', to='alternative3.owner'),
        ),
        migrations.AlterField(
            model_name='person',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='person', to='alternative3.owner'),
        ),
    ]
